/**
 * Known WordPress CSS Variables
 * List of CSS custom properties that WordPress uses and may generate false positives
 */

/**
 * WordPress Global Settings & Styles variables
 * These are dynamically generated by WordPress based on theme.json
 */
export const WORDPRESS_KNOWN_VARIABLES = [
  // Block Gap (spacing between blocks)
  '--wp--style--block-gap',

  // Color presets
  '--wp--preset--color--black',
  '--wp--preset--color--cyan-bluish-gray',
  '--wp--preset--color--white',
  '--wp--preset--color--pale-pink',
  '--wp--preset--color--vivid-red',
  '--wp--preset--color--luminous-vivid-orange',
  '--wp--preset--color--luminous-vivid-amber',
  '--wp--preset--color--light-green-cyan',
  '--wp--preset--color--vivid-green-cyan',
  '--wp--preset--color--pale-cyan-blue',
  '--wp--preset--color--vivid-cyan-blue',
  '--wp--preset--color--vivid-purple',

  // Gradient presets
  '--wp--preset--gradient--vivid-cyan-blue-to-vivid-purple',
  '--wp--preset--gradient--light-green-cyan-to-vivid-green-cyan',
  '--wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange',
  '--wp--preset--gradient--luminous-vivid-orange-to-vivid-red',
  '--wp--preset--gradient--very-light-gray-to-cyan-bluish-gray',
  '--wp--preset--gradient--cool-to-warm-spectrum',
  '--wp--preset--gradient--blush-light-purple',
  '--wp--preset--gradient--blush-bordeaux',
  '--wp--preset--gradient--luminous-dusk',
  '--wp--preset--gradient--pale-ocean',
  '--wp--preset--gradient--electric-grass',
  '--wp--preset--gradient--midnight',

  // Font size presets
  '--wp--preset--font-size--small',
  '--wp--preset--font-size--medium',
  '--wp--preset--font-size--large',
  '--wp--preset--font-size--x-large',
  '--wp--preset--font-size--xx-large',

  // Spacing presets
  '--wp--preset--spacing--20',
  '--wp--preset--spacing--30',
  '--wp--preset--spacing--40',
  '--wp--preset--spacing--50',
  '--wp--preset--spacing--60',
  '--wp--preset--spacing--70',
  '--wp--preset--spacing--80',

  // Shadow presets
  '--wp--preset--shadow--natural',
  '--wp--preset--shadow--deep',
  '--wp--preset--shadow--sharp',
  '--wp--preset--shadow--outlined',
  '--wp--preset--shadow--crisp',

  // Duotone presets
  '--wp--preset--duotone--dark-grayscale',
  '--wp--preset--duotone--grayscale',
  '--wp--preset--duotone--purple-yellow',
  '--wp--preset--duotone--blue-red',
  '--wp--preset--duotone--midnight',
  '--wp--preset--duotone--magenta-yellow',
  '--wp--preset--duotone--purple-green',
  '--wp--preset--duotone--blue-orange',
];

/**
 * WordPress variable patterns (regex)
 * These patterns match dynamically generated WordPress variables
 */
export const WORDPRESS_VARIABLE_PATTERNS = [
  /^--wp--preset--color--/,          // Any color preset
  /^--wp--preset--gradient--/,       // Any gradient preset
  /^--wp--preset--font-size--/,      // Any font size preset
  /^--wp--preset--font-family--/,    // Any font family preset
  /^--wp--preset--spacing--/,        // Any spacing preset
  /^--wp--preset--shadow--/,         // Any shadow preset
  /^--wp--preset--duotone--/,        // Any duotone preset
  /^--wp--custom--/,                 // Custom theme variables
  /^--wp--style--/,                  // Style variables (block-gap, etc.)
  /^--wp--lightbox-/,                // Lightbox component variables (single dash!)
  /^--wp--block--/,                  // Block-specific variables
  /^--wp--theme--/,                  // Theme variables
  /^--wp-admin--/,                   // WordPress admin bar variables
];

/**
 * Check if a CSS variable is a known WordPress variable
 * @param variableName The CSS variable name (with or without leading --)
 * @returns true if it's a known WordPress variable
 */
export function isWordPressVariable(variableName: string): boolean {
  // Normalize variable name (ensure it starts with --)
  const normalized = variableName.startsWith('--') ? variableName : `--${variableName}`;

  // Check exact matches
  if (WORDPRESS_KNOWN_VARIABLES.includes(normalized)) {
    return true;
  }

  // Check pattern matches
  return WORDPRESS_VARIABLE_PATTERNS.some(pattern => pattern.test(normalized));
}

/**
 * Get a suggestion message for WordPress variables
 * @param variableName The CSS variable name
 * @returns Suggestion message
 */
export function getWordPressSuggestion(variableName: string): string {
  return `This is a WordPress system variable (${variableName}). It may be declared dynamically by WordPress based on theme.json configuration. This is likely a false positive unless you're using a custom theme without proper Global Settings & Styles setup.`;
}
